services:
  - type: web
    name: tao-backend
    env: node
    plan: starter
    buildCommand: yarn install && yarn prisma generate && yarn build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /api
    autoDeploy: true 